# Configuration temporaire avec Swagger désactivé pour éviter l'erreur 500
spring:
  application:
    name: minio-file-service
  
  # Configuration multipart pour les gros fichiers
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
      file-size-threshold: 2KB
      location: /tmp
  
  # Configuration des timeouts
  mvc:
    async:
      request-timeout: 300000 # 5 minutes pour les gros uploads

# Configuration MinIO pour production
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket:
    songs: ${MINIO_BUCKET_SONGS:minio-songs}
    images: ${MINIO_BUCKET_IMAGES:minio-images}
    videos: ${MINIO_BUCKET_VIDEOS:minio-videos}
    photos: ${MINIO_BUCKET_PHOTOS:minio-photos}
    documents: ${MINIO_BUCKET_DOCUMENTS:minio-documents}
    archives: ${MINIO_BUCKET_ARCHIVES:minio-archives}
    files: ${MINIO_BUCKET_FILES:minio-files}

# Configuration des logs pour production
logging:
  level:
    root: INFO
    minio.minio.minio: INFO
    org.springframework.web: WARN
    io.minio: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/minio-file-service.log
    max-size: 100MB
    max-history: 10

# Configuration Actuator pour monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    diskspace:
      enabled: true
      path: /app/data
      threshold: 100MB
  prometheus:
    metrics:
      export:
        enabled: true

# Configuration Swagger/OpenAPI - DÉSACTIVÉ TEMPORAIREMENT
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Configuration du serveur
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true
  error:
    include-stacktrace: never
    include-message: always
  forward-headers-strategy: native
